### PR TITLE
updated docker stuff, added vscode devcontainer

### PR DESCRIPTION
**Pull request by NoahIles**
Idk if your secret key thing was working but it got commented out you should be able to do that through `docker exec`...

### CODE REVIEW

**Comment by Kapral67** [comment]
Having issues with using dev containers in vscode on arch linux:
```log
[2023-02-28T08:14:48.873Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-02-28T08:14:49.022Z] Stop (149 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-02-28T08:14:49.023Z] 1.42
[2023-02-28T08:14:49.044Z] Start: Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/mkapral/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/mkapral/GitHub/Shoe-Expert --log-level debug --log-format json --config /home/mkapral/GitHub/Shoe-Expert/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-02-28T08:14:49.290Z] (node:253658) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-02-28T08:14:49.290Z] (Use `code --trace-deprecation ...` to show where the warning was created)
[2023-02-28T08:14:49.293Z] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 6.1.12-arch1-1 x64.
[2023-02-28T08:14:49.293Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/mkapral/GitHub/Shoe-Expert
[2023-02-28T08:14:49.343Z] Stop (50 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/mkapral/GitHub/Shoe-Expert
[2023-02-28T08:14:49.343Z] Command failed: docker ps -q -a --filter label=devcontainer.local_folder=/home/mkapral/GitHub/Shoe-Expert
[2023-02-28T08:14:49.348Z] Stop (304 ms): Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/mkapral/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/mkapral/GitHub/Shoe-Expert --log-level debug --log-format json --config /home/mkapral/GitHub/Shoe-Expert/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-02-28T08:14:49.348Z] Exit code 1
```

Initially I thought it was a problem with the vscode docker extension, but I added the DOCKER_HOST env variable to the extension's settings pointing to `unix:///run/user/1000/docker.sock` as I use [docker in rootless](https://aur.archlinux.org/packages/docker-rootless-extras), and the container doesn't build still. The log shows that a `docker ps ...` command fails, but it executes code 0 when I run it manually. Not sure yet what the issue is, any suggestions?

It seems to build fine on my mac, but I haven't tried much else there.

**Comment by NoahIles** [comment]
The ways I would recommend interacting with the app IMO 
- `Docker compose up` (with or without a -d flag based on personal preference 
-  `Docker compose down` ( must be in the folder with the compose.yml for this to work) 
- or use vscode to build and run a devcontainer with the command palette (need remote extension pack for this to work)

**Comment by Kapral67** [comment]
I'm thinking that using the command palette in vscode is going to be easiest for everyone. That requires the remote extension as well as dev-containers extension in vscode?

**Comment by Kapral67** [comment]
Is docker compose up/down similar to docker start and docker stop?

**Comment by NoahIles** [comment]
IF you have resolved this with a vscdoe settings I recommend adding it to the .devcontainer config

**Comment by Kapral67** [comment]
> If you have resolved this with a vscode settings I recommend adding it to the .devcontainer config

I'm pretty sure it was an issue with my docker setup locally since I didn't have the issue on macOS

**Comment by NoahIles** [comment]
> I'm thinking that using the command palette in vscode is going to be easiest for everyone. That requires the remote extension as well as dev-containers extension in vscode?

Yep. yeah it is the simplest way to interact...with it automatically stops it for you to...
Most of the time a popup will come up prompting to open it...just gotta teach users how to tell they are actually in the container....

a side note if you add docker as a plugin for oh-my-zsh  you get a bunch of docker aliases like `dcup` = docker compose up  `dcdn` = docker compose down`.

**Comment by Kapral67** [comment]
Oh that's neat. I use the plugin for systemd, but I'll have to add the docker one to my zshrc

**Review by Kapral67 — APPROVED** [review]
Thanks @NoahIles , this is certainly superior to what we had previously in place.

**Comment by NoahIles** [comment]
Your cake just needed some icing. :P

**Pull request merged**
